### ISSUE TITLE
CH 10-2 프로세스와 스레드

### ISSUE THREAD

**Issue by Sleepingoff** [OurStudyLog/operatingsystem#14]
10-2 프로세스 상태와 계층 구조
__프로세스 상태
__프로세스 계층 구조
__프로세스 생성 기법
[4가지 키워드로 정리하는 핵심 포인트]
[확인 문제]

**Comment by Sleepingoff** [comment]
- 프로세스 상태와 계층 구조, 프로세스 생성기법에서 사용하는 시스템 호출
- 프로세스와 스레드의 차이점

**Comment by ImSeon01** [comment]
프로세스와 스레드, 멀티프로세스와 멀티스레드 등 차이점을 구별을 잘해주셔서 좋았습니다.

무엇보다도 직접 그려보는 시간을 통해 이해도를 높일 수 있는 시간을 가져서 좋았습니다.

**Comment by atoonatoo** [comment]
피피티식으로 깔끔하게 정리해주셔서 분단별로 내용에 집중하기 좋았습니다.
그림식 질문으로 프로세스 상태 다이어그램의 복습하는 시간을 좋았습니다.
