### ISSUE TITLE
CH 12-1 동기화란

### ISSUE THREAD

**Issue by Sleepingoff** [OurStudyLog/operatingsystem#20]
12-1 동기화란
__동기화의 의미
__ 생산자와 소비자 문제
__공유 자원과 임계 구역

**Comment by Sleepingoff** [comment]
동기화, 생산자와 소비자 문제, 공유자원과 임계구역

**Comment by ImSeon01** [comment]
동기화가 무엇인지 실제 코드와 함께 설명해주셔서  이해가 잘 되고 좋았습니다. 1장 범위를 핵심 개념 위주로 잘 설명해 주셨습니다.

**Comment by uzjaee** [comment]
먼저 전반적인 내용을 설명한 뒤 이론 글을 같이 읽으니 더 이해가 잘되었습니다.
