### ISSUE TITLE
CH 07-1 다양한 보조기억장치

### ISSUE THREAD

**Issue by Sleepingoff** [OurStudyLog/operatingsystem#6]
- 하드 디스크
- 플래시 메모리

**Comment by Sleepingoff** [comment]
## PLAN

- 하드 디스크의 구조
- 플래터와 관련한 개념
- 플래시 메모리의 단위

**Comment by uzjaee** [comment]
알아야하는 개념을 놓치지않고 알려주었습니다.
퀴즈또한 핵심적인 내용을 담을 수 있도록 출제해주었습니다.

**Comment by ImSeon01** [comment]
좋은 발표 감사합니다.
AND 연산과 OR 연산에 대한 설명을 조금 더 부연 설명해드립니다.
AND 연산은 A && B 수행할 때 A가 false이면 B에 대한 판단을 하지 않습니다.
하지만 OR 연산은 A || B 수행할 때 A가 false여도 B를 수행합니다.

**Comment by atoonatoo** [comment]
시간내에 핵심내용을 맞춰 발표를 완수한 부분에서 좋았습니다
오가니제이션의 활용에 대해 선두적으로 활용해주셔서 추후 어떻게 사용해야할지 좋은 참고가 되었습니다.
