### ISSUE TITLE
CH 07-2 RAID의 정의와 종류

### ISSUE THREAD

**Issue by Sleepingoff** [OurStudyLog/operatingsystem#7]
- RAID의 정의
- RAID의 종류

**Comment by atoonatoo** [comment]
난센스 퀴즈 좋았습니다 !!
레이드 종류에 대해 그림도형을 표현으로 잘 발표해주셨습니다.

**Comment by uzjaee** [comment]
ppt 이미지를 통해 직관적인 설명을 해주셨습니다 .
각각을 비교하여 핵심적인 정보를 전달해주었습니😊

**Comment by Sleepingoff** [comment]
RAID 50에 대해서 더 궁금합니다.
퀴즈로 RAID를 쓰게 되면 어떤 것을 쓸지 생각해보는 것도 좋았습니다.
