### ISSUE TITLE
CH 08-1 장치 컨트롤러와 장치 드라이버

### ISSUE THREAD

**Issue by Sleepingoff** [OurStudyLog/operatingsystem#8]
- 장치 컨트롤러
- 장치 드라이버

**Comment by uzjaee** [comment]
장치컨트롤러 
  역할
  구조
장치 드라이버

**Comment by Sleepingoff** [comment]
핵심적인 부분을 짚어주어서 좋았습니다.
이미지 경로에 대해서 어떻게 할지 같이 생각해보면 좋을 것 같아요!

**Comment by ImSeon01** [comment]
핵심적인 내용을 압축하여 말씀해주시고 추가적인 준비 자료도 준비해 설명해주셔서 감사합니다.

**Comment by atoonatoo** [comment]
핵심을 잘파악하셨습니다.
추후 공부할 사전 지식을 파악하기 위한 정보들을 잘 발표하셨습니다.
