### ISSUE TITLE
CH 08-2 다양한 입출력 방버

### ISSUE THREAD

**Issue by Sleepingoff** [OurStudyLog/operatingsystem#9]
- 프로그램 입출력
- 인터럽트 기반 입출력
- DMA 입출력

**Comment by ImSeon01** [comment]
가장 어려워서 접근하기 어려웠던 챕터였는데 김동욱 님께서 잘 설명해주셔서 감사합니다. 오늘 제일 고생하셨습니다.

**Comment by Sleepingoff** [comment]
어려운 내용인데 좋은 발표 감사합니다. 정리를 할 때 좀 더 체계적으로 하면 좋을 것 같습니다. 리스트의 depth가 깊어져서 정리본을 볼 때 헷갈렸던 부분이 있었습니다.

**Comment by uzjaee** [comment]
어렵고 추상적인 내용을 최대한 정리해주시려는게 발표중 느껴졌습니다.
특히 비유적인 내용을 통해 설명하려는게 도움이 되었습니다. 😙
